//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacebookCrawlerAllInOne
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACEBOOK_USER
    {
        public string ID { get; set; }
        public string NAME { get; set; }
        public string PROFILE_LINK { get; set; }
        public string GET_BY { get; set; }
        public Nullable<System.DateTime> GET_TIME { get; set; }
        public string LANGUAGE { get; set; }
        public Nullable<bool> CHECKED { get; set; }
    }
}
