//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacebookCrawlerAllInOne
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FBCrawlerV2Entities : DbContext
    {
        public FBCrawlerV2Entities()
            : base("name=FBCrawlerV2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<FACEBOOK_USER> FACEBOOK_USER { get; set; }
        public DbSet<INFO> INFOes { get; set; }
    }
}
