//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacebookCrawlerAllInOne
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFO
    {
        public string ID { get; set; }
        public string CONTACT_INFO { get; set; }
        public string LIVING { get; set; }
        public string EDUCATION { get; set; }
        public string YEAR_OVERVIEW { get; set; }
        public string OVERVIEW { get; set; }
    }
}
